language: r
r:
  - oldrel
  - release
  - devel
env:
  global:
    - R_CHECK_ARGS="--as-cran"
cache: packages
install:
  - Rscript -e 'install.packages("devtools", repos = "http://cran.rstudio.com")'
